version: '3.7'

services:
  codesuite-db:
    image: mysql
    restart: on-failure
      #network_mode: "host"
    ports: 
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=compiler
      - MYSQL_USER=compiler
      - MYSQL_PASSWORD=compiler
    networks:
      - backend

  codesuite-frontend:
    image: codesuite-frontend
    restart: on-failure
      #network_mode: "host"
    depends_on:
      - codesuite-backend
    ports:
      - 3000:3000
    networks:
      - frontend
 
  codesuite-backend:
    image: codesuite-backend
    restart: on-failure
      #network_mode: "host"
    depends_on:
      - codesuite-db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=compiler-db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=compiler
      - DATABASE_NAME=compiler
      - DATABASE_PORT=3306
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:
